# Generated by Django 3.2.4 on 2022-11-10 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0011_alter_registration_domain'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='phone',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='registration',
            name='roll_no',
            field=models.CharField(blank=True, max_length=13, null=True),
        ),
    ]
