# Generated by Django 3.2.4 on 2022-11-10 19:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0012_auto_20221111_0107'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registration',
            name='behance_username',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='domain',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='github_username',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='hacker_rank_username',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='roll_no',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='skills',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='your_work',
        ),
        migrations.AlterField(
            model_name='registration',
            name='year',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='Core.year'),
        ),
    ]
