# Generated by Django 3.2.4 on 2022-11-11 04:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0016_remove_emailtemplate_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailtemplate',
            name='event',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='email_template', serialize=False, to='Core.event'),
        ),
    ]
